baseURL = 'http://chettyarun.com/'
languageCode = 'en'
title = 'Chetty Arun'
theme = 'hugo-blog-awesome'

# This defines how dates are formatted
defaultContentLanguage = "en-gb"

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] # ignore error of loading additional scripts.

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

[menu]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 10
  [[menu.main]]
    pageRef="bio"
    name = 'Bio'
    url = '/bio/'
    weight = 20

[params]
  sitename = "Chetty Arun"
  defaultColor = "light" # set color mode: dark, light, auto
  # Setting it to 'auto' applies the color scheme based on the visitor's device color preference.If you don't specify anything, ignore this parameter, or leave it blank,
  # the default value is set to 'auto'.
  
  # You can take a look at layouts/index.html for more information.
  description = "Culture head at Razorpay. A part of the core founding team. Used to head the design team before"
  mainSections = ['posts']
  toc = false # set to false to disable table of contents 'globally'
  goToTop = true # set to false to disable 'go to top' button
  additionalScripts = ['js/custom.js', 'js/custom-2.js']
  # Will try to load 'assets/js/custom.js' and 'assets/js/custom-2.js'.
  # Your custom scripts will be concatinated to one file `custom.js`.
  # When building for production it will be minified.
  # The file `custom.js` is loaded on each page (before body tag ends).

  [params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Hi, I'm Chetty Arun"
  name = "Chetty Arun"
  description = "I am a part of the core founding team at [Razorpay](https://razorpay.com) and I know a little about a lot of things. Besides my work, I'm into advising startups on design & culture, lifting weights & staying fit, and following a healthy lifestyle. I'm also an avid reader, especially of fantasy and science fiction."

  [params.now]
  description = "Currently, I'm the Culture Head at Razorpay. Previously, I headed the design team. As the Culture Head, I am responsible for defining, promoting, and reviewing everything about our core culture values. A big part of my work is to ensure that our values are lived and celebrated in every corner of Razorpay. Check out a quick [Twitter AMA](https://twitter.com/ChettyArun/status/1656950855848038402) session where I highlighted my role as the Culture Head."



  # Social icons

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/chettyarun"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/chettyarun"

[[params.socialIcons]]
name = "email"
url = "mailto:me@chettyarun.com?Subject=I saw your website! Hello!"

# Adding a new post
# use "hugo new posts/new-post.md" and that creates a new md file in /posts Or, just create a new folder inside /posts with the same title and create a new md file in that folder 
# check the examplesite folder posts to check the md styles
# remove draft: true propoerty in the md file and git push